### ISSUE TITLE
View IDs when using Kotlin Android Extensions

### ISSUE THREAD

**Issue by jaranflaath** [android/kotlin-guides#46]
When using the Kotlin Android Extensions plugin (https://kotlinlang.org/docs/tutorials/android-plugin.html) which automatically provides properties for your views, so you do not have to do lookup via findViewById, the naming convention for these IDs are in many cases in conflict with variable and property naming conventions. Should ID's follow camelCase patterns, or should property names deviate from the convention in this situation?  

I think the style guide would benefit from saying something about this, but there is probably a discussion that needs to be had before we can define any style guide for this - hence this post. 

My personal view is that any ID naming conventions should yield to Kotlin naming conventions in this case, as the impact of changing the naming convention will have a bigger positive impact on code readability than the negative impact on layout file readability. 

Commence discussion! :)

**Comment by JakeWharton** [comment]
My biggest problem here is that the convention used for these IDs should not change based on your decision to use a tool (in this case, the extensions plugin). And unless we're going to recommend that camelCase be used all the time and for both languages, a conditional rule is worse than a single one.

Beyond that, I'm a strong believer in [not altering your naming conventions based on where you eventually consume them][1]. The framework and support libraries will continue to use snake_case because their consistency is a higher value.

 [1]: https://publicobject.com/2016/01/20/strict-naming-conventions-are-a-liability/

**Comment by JakeWharton** [comment]
Also the guide is really only for the Kotlin language so it doesn't fit into any page we currently have.

**Comment by jaranflaath** [comment]
Thanks for your feedback, Jake. I see your points, and I do agree that we developers can sometimes get quite uptight about our naming conventions and rules - which can lead to uneccessary work. However, in this case, where (as far as I know, please correct me if I am wrong) there are no clear guidelines on view ID's in Android, which in my world means we could adapt these to match any guidelines set for using these IDs in the Kotlin code. 

The style guide clearly states that the guidelines are for _Android coding standards_ in the Kotlin programming language, so I am not sure I agree that there should be no place for guidelines related to libraries commonly used to make our coding more efficient and readable. 

Anyways, thanks for taking your time to respond and for putting together a style guide in the first place :)
