### ISSUE TITLE
Consider 120 character limit

### ISSUE THREAD

**Issue by ZakTaccardi** [android/kotlin-guides#67]
What's the reasoning behind having a 100 character limit? I advocate bumping it to 120.

### Pros (of 120 limit)
- Allows the developer to be more expressive and write more readable code
  - helps make up for the lack of 2/2/4 indenting
  - kotlin's coroutines and `let`/`run`/etc functions add a lot of indenting
- Jetbrains Kotlin style guide does not specify a column limit, so this doesn't conflict
- Monitors are more than wide enough today to accommodate this

### Cons
- [Google Java style](https://google.github.io/styleguide/javaguide.html#s4.4-column-limit) is 100
- IntelliJ doesn't seem to be able to support different line lengths per file type

> Note: The primary goal for line wrapping is to have clear code, not necessarily code that fits in the smallest number of lines.

I believe 120 helps achieve this goal by not forcing line breaks when they don't make sense. Though of course this could be abused.

**Comment by handstandsam** [comment]
Not sure where 100 came from.  I don't see how 120 is much different.

Doesn't Google have anonymized Android Studio statistics about screen resolution and density?  I think this would be a key factor in determining line length to best support users of Android Studio.

It does seem like `2/2/4` indenting would make this issue go away.

**Comment by ZakTaccardi** [comment]
> It does seem like `2/2/4` indenting would make this issue go away.

Unfortunately this would conflict with [JetBrains' Kotlin style guide](https://kotlinlang.org/docs/reference/coding-conventions.html#formatting), which requires a 4 space indent.

@JakeWharton is a big fan of the `2` space indent so I'm sure he would have gone with that if it were feasible.

**Comment by JakeWharton** [comment]
Indeed I am, and it leads me into my first point about this feature request:

This is a guide for those searching for guidance. It is not a mandate or requirement and we aim not to be either. You won't see any of my personal Kotlin projects use four space indent because I'm not searching for guidance there. I have made my own decision based on my historical usage of tabs, 4 space, and 2 space as to what works best for me. You are free to exercise your judgement in column length as well.

> Monitors are more than wide enough today to accommodate this

Monitors have been wide enough to accommodate more than 100 for 15 years. Column limits allow stacking files horizontally so that you can see more files, not more content. It also enables the use of side-by-side diffing more effectively. There's diminishing returns on increasing the column count.

Ultimately we're not going to change because of the Google Java style guide and symmetry with it is more important. But if it doesn't work for you, please chose something that does. We're not aiming to be a standard!
